/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package br.com.source.knowledge.model.avdl;

@org.apache.avro.specific.AvroGenerated
public interface TransactionAVDL {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"TransactionAVDL\",\"namespace\":\"br.com.source.knowledge.model.avdl\",\"types\":[{\"type\":\"record\",\"name\":\"PersonAVDL\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"TransactionAVDL\",\"fields\":[{\"name\":\"transactionId\",\"type\":\"string\"},{\"name\":\"person\",\"type\":\"PersonAVDL\"},{\"name\":\"mother\",\"type\":\"PersonAVDL\"}]}],\"messages\":{}}");

  @org.apache.avro.specific.AvroGenerated
  public interface Callback extends TransactionAVDL {
    public static final org.apache.avro.Protocol PROTOCOL = br.com.source.knowledge.model.avdl.TransactionAVDL.PROTOCOL;
  }
}